@HttpClientMethods_HostAddress = http://localhost:5099

### GetAsync(String)

GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/count
Accept: application/json

### GetAsync(String, CancellationToken)

GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos?page=1&perPage=1&totalPages=1&cid=1
Accept: application/json

### GetAsync(String, HttpCompletionOption)

GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/stream?page=1&perPage=10&totalPages=2
Accept: application/json

### GetAsync(String, HttpCompletionOption, CancellationToken)

GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/stream/cancel?page=1&perPage=10&totalPages=1&cid=1
Accept: application/json






### GetAsync_GetCommitsCountAsync               ----    GetAsync(Uri)

GET {{HttpClientMethods_HostAddress}}/getasync/repos/dotnet/efcore/commits/count
Accept: application/json

### GetAsync_GetCommitsAsync                    ----    GetAsync(Uri, CancellationToken)

GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/efcore/commits?page=1&perPage=10&totalPages=1&cid=1
Accept: application/json


### GetAsync_GetCommitsStreamAsync              ----    GetAsync(Uri, HttpCompletionOption)
GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/efcore/commits/streams?page=1&perPage=10&totalPages=1
Accept: application/json


### GetAsync_GetCommitsStreamCancelAsync        ----    GetAsync(Uri, HttpCompletionOption, CancellationToken)
GET {{HttpClientMethods_HostAddress}}/getasync/orgs/dotnet/repos/efcore/commits/streams/cancel?page=1&perPage=10&totalPages=1&cid=1
Accept: application/json