@username = massielcr
@owner = massielcr
@repo_test = my-test-http-repo
@repo = net-api

### HttpMethod.Head

GET {{HostAddress}}/sendasync/users/{{username}}/avatar HTTP/2
Accept: application/json

### HttpMethod.Options

GET {{HostAddress}}/sendasync/users/{{username}}/options  HTTP/2
Accept: application/json





### Task

POST {{HostAddress}}/sendasync/{{owner}}/{{repo_test}}/issues?cid=1&to=30 HTTP/2
Accept: application/json
Content-Type: application/json
{
  "title": "File Todo",
  "body": "Provision File"
}

### Task<T>

GET {{HostAddress}}/sendasync/{{owner}}/repos/{{repo}}?cid=1&to=30 HTTP/2
Accept: application/json

### Task<T> Task.WhenAny

POST {{HostAddress}}/sendasync/anyrepo?cid=1&to=30 HTTP/2
Accept: application/json
Content-Type: application/json
{
   "owners": [
      "dotnet",
      "massielcr"
   ]
}

### Task<T> Task.WhenAll

POST {{HostAddress}}/sendasync/allrepos?cid=1&to=30 HTTP/2
Accept: application/json
Content-Type: application/json
{
   "owners": [
      "dotnet",
      "massielcr"
   ]
}

### Task.WhenEach

GET {{HostAddress}}/sendasync/{{owner}}/eachrepos?cid=1&to=30 HTTP/2
Accept: application/json



### GetAsync(String, CancellationToken) - CancellationToken

GET {{HostAddress}}/sendasync/orgs/dotnet/repos?page=1&perPage=5&totalPages=2&cid=1
Accept: application/json

### GetAsync(String, CancellationToken) - CancellationToken

GET {{HostAddress}}/sendasync/orgs/dotnet/repos/parallel?page=1&perPage=5&totalPages=2&cid=1  HTTP/2
Accept: application/json