@owner = massielcr
@repo = my-test-http-repo

### DeleteAsync(String)                                ----    DeleteAsync_DeleteRepositoryIssueAsync
DELETE {{HostAddress}}/deleteasync/repos/{{owner}}/{{repo}}/issues/1/unlock HTTP/2
Accept : application/json

### DeleteAsync(String, CancellationToken)             ----    PutAsync_LockRepositoryIssuesAsync
POST {{HostAddress}}/deleteasync/repos/{{owner}}/{{repo}}/issues/unlockbatch?cid=1 HTTP/2
Accept : application/json
Content-Type: application/json
[1,2,3,4,5,6,7,8]

### DeleteAsync(Uri)                                    ----    PutAsync_LockRepositoryIssueAsync
DELETE {{HostAddress}}/deleteasync/repos/{{owner}}/{{repo}}/issues/2/unlockuri HTTP/2
Accept : application/json

### DeleteAsync(Uri, CancellationToken)                 ----    PutAsync_LockRepositoryIssuesStreamAsync
POST {{HostAddress}}/deleteasync/repos/{{owner}}/{{repo}}/issues/unlockbatchstream?cid=1 HTTP/2
Accept : application/json
Content-Type: application/json
[1,2,3,4,5,6,7,8]