@owner = dotnet
@repo1 = runtime

### GetAsync(String)                            ----    GetAsync_GetRepositoriesCountAsync

GET {{HostAddress}}/getasyncapi/orgs/{{owner}}/repos/count HTTP/2
Accept: application/json

### GetAsync(String, CancellationToken)         ----    GetAsync_GetRepositoriesAsync

GET {{HostAddress}}/getasyncapi/orgs/{{owner}}/repos?page=1&perPage=5&totalPages=1&cid=1 HTTP/2
Accept: application/json

### GetAsync(String, HttpCompletionOption)

GET {{HostAddress}}/getasyncapi/repos/{{owner}}/{{repo1}}/readme HTTP/2
Accept: text/html

### GetAsync(String, HttpCompletionOption, CancellationToken)

GET {{HostAddress}}/getasyncapi/orgs/{{owner}}/repos/streamcancel?perPage=10&cid=1 HTTP/2
Accept: application/json



### GetAsync_GetCommitsCountAsync               ----    GetAsync(Uri)

GET {{HostAddress}}/getasyncapi/repos/dotnet/efcore/commits/count HTTP/2
Accept: application/json

### GetAsync_GetCommitsAsync                    ----    GetAsync(Uri, CancellationToken)

GET {{HostAddress}}/getasyncapi/orgs/dotnet/repos/efcore/commits?page=1&perPage=10&totalPages=1&cid=1 HTTP/2
Accept: application/json


### GetAsync_GetCommitsStreamAsync              ----    GetAsync(Uri, HttpCompletionOption)

GET {{HostAddress}}/getasyncapi/orgs/dotnet/repos/efcore/commits/streams?page=1&perPage=10&totalPages=1 HTTP/2
Accept: application/json


### GetAsync_GetCommitsStreamCancelAsync        ----    GetAsync(Uri, HttpCompletionOption, CancellationToken)

GET {{HostAddress}}/getasyncapi/orgs/dotnet/repos/efcore/commits/streams/cancel?page=1&perPage=10&totalPages=1&cid=1 HTTP/2
Accept: application/json