@username = massielcr

### GetByteArrayAsync(String)   ---    GetByteArrayAsync_DownloadAvatarStringAsync

GET {{HostAddress}}/getbytearrayasyncapi/users/{{username}}/downloadavatarstring?overwrite=true
Accept: application/json

### GetByteArrayAsync(Uri)      ---    GetByteArrayAsync_DownloadAvatarUriAsync    

GET {{HostAddress}}/getbytearrayasyncapi/users/{{username}}/downloadavataruri?overwrite=true
Accept: application/json

