@owner = dotnet
@repo1 = runtime
@repo2 = aspnetcore


### GetStringAsync(String)   ---    GetStringAsync_GetRepositoryReadmeStringAsync

GET {{HostAddress}}/getstringasyncapi/{{owner}}/repos/{{repo1}}/readmestring HTTP/2
Accept: text/markdown

### GetStringAsync(Uri)      ---    GetStringAsync_GetRepositoryReadmeUriAsync

GET {{HostAddress}}/getstringasyncapi/{{owner}}/repos/{{repo2}}/readmeuri HTTP/2
Accept: text/markdown
