@username = massielcr

### GetStreamAsync(String)   ---    GetStreamAsync_GetRepositoryReadmeStringAsync

GET {{HostAddress}}/getstreamasyncapi/users/{{username}}/downloadavatarstring?overwrite=true HTTP/2
Accept: application/json

### GetStreamAsync(Uri)      ---    GetStreamAsync_GetRepositoryReadmeUriAsync

GET {{HostAddress}}/getstreamasyncapi/users/{{username}}/downloadavataruri?overwrite=true HTTP/2
Accept: application/json