@owner = dotnet


### GetStringAsync(String)   ---    GetStringAsync_GetRepositoryReadmeStringAsync
@repo1 = runtime

GET {{HostAddress}}/getstringasyncapi/{{owner}}/repos/{{repo1}}/readmestring
Accept: text/markdown

### GetStringAsync(Uri)      ---    GetStringAsync_GetRepositoryReadmeUriAsync
@repo2 = aspnetcore

GET {{HostAddress}}/getstringasyncapi/{{owner}}/repos/{{repo2}}/readmeuri
Accept: text/markdown
