### Create a Personal Repository via GitHub REST API

POST {{HostAddress}}/postasync/repos
Accept: application/vnd.github+json
User-Agent: MyTestService
Content-Type: application/json
{
  "name": "my-test-http-repo",
  "description": "Created using an .http file!",
  "private": true,
  "auto_init": true
}
