### GetAsync(String, CancellationToken) - CancellationToken

GET {{HostAddress}}/sendasync/orgs/dotnet/repos?page=1&perPage=5&totalPages=2&cid=1
Accept: application/json

### GetAsync(String, CancellationToken) - CancellationToken

GET {{HostAddress}}/sendasync/orgs/dotnet/repos/parallel?page=1&perPage=5&totalPages=2&cid=1
Accept: application/json
