@owner = massielcr
@repo = my-test-http-repo

### PutAsync(String, HttpContent)                       ----    PutAsync_UpdateRepositoryTopicsAsync
PUT {{HostAddress}}/putasync/repos/{{owner}}/{{repo}}/topics HTTP/2
Accept : application/json
Content-Type: application/json
{
  "names": [
    "httpclient",
    "api",
    "csharp",
    "netcore"
  ]
}

### PutAsync(String, HttpContent, CancellationToken)    ----    PutAsync_LockRepositoryIssuesAsync
PUT {{HostAddress}}/putasync/repos/{{owner}}/{{repo}}/issues/lockbatch?cid=1 HTTP/2
Accept : application/json
Content-Type: application/json
{
  "issues": [
    {
     "issue_number": "1",
     "lock_reason": "off-topic"  
    },
    {
     "issue_number": "2",
     "lock_reason": "off-topic"  
    },
    {
     "issue_number": "3",
     "lock_reason": "off-topic" 
    },
    {
     "issue_number": "4",
     "lock_reason": "off-topic"  
    },
    {
     "issue_number": "5",
     "lock_reason": "off-topic"   
    },
    {
     "issue_number": "6",
     "lock_reason": "off-topic" 
    },
    {
     "issue_number": "7",
     "lock_reason": "off-topic" 
    },
    {
     "issue_number": "8",
     "lock_reason": "off-topic" 
    }
  ]
}

### PutAsync(Uri, HttpContent)                          ----    PutAsync_LockRepositoryIssueAsync
PUT {{HostAddress}}/putasync/repos/{{owner}}/{{repo}}/issues/lock HTTP/2
Accept : application/json
Content-Type: application/json
{
  "issue_number": "9",
  "lock_reason": "too heated" 
}

### PutAsync(Uri, HttpContent, CancellationToken)       ----    PutAsync_LockRepositoryIssuesStreamAsync
PUT {{HostAddress}}/putasync/repos/{{owner}}/{{repo}}/issues/lockbatchstream?cid=1 HTTP/2
Accept : application/json
Content-Type: application/json
{
  "issues": [
    {
     "issue_number": "1",
     "lock_reason": "resolved"  
    },
    {
     "issue_number": "2",
     "lock_reason": "resolved"   
    },
    {
     "issue_number": "3",
     "lock_reason": "resolved" 
    },
    {
     "issue_number": "4",
     "lock_reason": "resolved"  
    },
    {
     "issue_number": "5",
     "lock_reason": "resolved" 
    },
    {
     "issue_number": "6",
     "lock_reason": "resolved" 
    },
    {
     "issue_number": "7",
     "lock_reason": "resolved"  
    },
    {
     "issue_number": "8",
     "lock_reason": "resolved"  
    }
  ]
}