export const pies = [
  {
    id: 'p1',
    name: 'Apple Pie',
    price: 12.5,
    inStock: true,
    averageRating: 4.5,
    category: 'fruit',
  },
  {
    id: 'p2',
    name: 'Cherry Pie',
    price: 13.0,
    inStock: false,
    averageRating: 4.2,
    category: 'fruit',
  },
  {
    id: 'p3',
    name: 'Pumpkin Pie',
    price: 11.0,
    inStock: true,
    averageRating: 4.7,
    category: 'seasonal',
  },
  {
    id: 'p4',
    name: 'Blueberry Pie',
    price: 14.0,
    inStock: true,
    averageRating: 4.3,
    category: 'fruit',
  },
  {
    id: 'p5',
    name: 'Strawberry Pie',
    price: 13.5,
    inStock: true,
    averageRating: 4.6,
    category: 'fruit',
  },
  {
    id: 'p6',
    name: 'Pecan Pie',
    price: 15.0,
    inStock: false,
    averageRating: 4.8,
    category: 'seasonal',
  },
  {
    id: 'p7',
    name: 'Key Lime Pie',
    price: 12.0,
    inStock: true,
    averageRating: 4.4,
    category: 'fruit',
  },
  {
    id: 'p8',
    name: 'Chocolate Cream Pie',
    price: 13.5,
    inStock: true,
    averageRating: 4.1,
    category: 'cheesecake',
  },
  {
    id: 'p9',
    name: 'Banana Cream Pie',
    price: 12.5,
    inStock: true,
    averageRating: 4.0,
    category: 'cheesecake',
  },
  {
    id: 'p10',
    name: 'Lemon Meringue Pie',
    price: 14.5,
    inStock: false,
    averageRating: 4.9,
    category: 'cheesecake',
  },
];
