@HttpClientMethods_HostAddress = http://localhost:5099

### GetAsync(String)

GET {{HttpClientMethods_HostAddress}}/repos/count
Accept: application/json

### GetAsync(String, HttpCompletionOption)



### GetAsync(String, CancellationToken)

GET {{HttpClientMethods_HostAddress}}/orgs/dotnet/repos/efcore/commits?page=1&perPage=10&totalPages=1&cid=1
Accept: application/json


### GetAsync(String, HttpCompletionOption, CancellationToken)






### GetAsync(Uri)

GET {{HttpClientMethods_HostAddress}}/repos
Accept: application/json


### GetAsync(Uri, HttpCompletionOption)


### GetAsync(Uri, CancellationToken)


### GetAsync(Uri, HttpCompletionOption, CancellationToken)
GET {{HttpClientMethods_HostAddress}}/orgs/dotnet/repos/efcore/commitstream?page=1&perPage=10&totalPages=1&cid=1
Accept: application/json