@HttpClientMethods_HostAddress = http://localhost:5099


GET {{HttpClientMethods_HostAddress}}/repos/count
Accept: application/json

###

GET {{HttpClientMethods_HostAddress}}/repos
Accept: application/json

###
